---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmreleaseproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmreleaseproxies/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmreleaseproxies/status
  verbs:
  - get
  - patch
  - update
